name: test_dotnet_tool
on:
  workflow_dispatch:

jobs:
  toolinstall:
    name: "Tool install & test"

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2

    - name: Set up .NET 8 SDK
      id: dotnet_install
      if: steps.checkout.conclusion == 'success'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    
    - name: install tool
      id: install_tool
      if: steps.dotnet_install.conclusion == 'success'
      run: |
        make installtool psNuGetSourceName=PSGallery
