name: test_install
on:
  workflow_dispatch:

jobs:
  moduleinstall:
    name: "Install Module & Test"

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2

    - name: install module
      id: install_module
      if: steps.checkout.conclusion == 'success'
      run: |
        make installmodule psNuGetSourceName=PSGallery

    - name: run powershell tests
      id: ps_tests_install
      if: steps.install_module.conclusion == 'success'
      run: |
        make pstestspostinstall psNuGetSourceName=PSGallery

  toolinstall:
    name: "Tool install & test"

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2

    - name: Set up .NET 8 SDK
      id: dotnet_install
      if: steps.checkout.conclusion == 'success'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    
    - name: install tool
      id: install_tool
      if: steps.dotnet_install.conclusion == 'success'
      run: |
        make installtool psNuGetSourceName=PSGallery